version: 40
jobs:
- name: CICD
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: SUCCESSFUL
    optional: false
  - !UseTemplateStep
    name: Detect Version
    templateName: Python Detect Version
    condition: SUCCESSFUL
    optional: false
  - !UseTemplateStep
    name: UV Cache and Sync
    templateName: UV Cache and Sync
    condition: SUCCESSFUL
    optional: false
  - !UseTemplateStep
    name: Linter
    templateName: Python Lint
    condition: SUCCESSFUL
    optional: false
  - !CommandStep
    name: Build Library
    runInContainer: true
    image: ghcr.io/astral-sh/uv:python3.13-bookworm-slim
    interpreter: !DefaultInterpreter
      commands: |
        uv build --python-preference=only-managed --cache-dir .uvcache
    envVars:
    - name: UV_PYTHON_INSTALL_DIR
      value: /onedev-build/workspace/.uvpython
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - !PublishArtifactStep
    name: Publish Artifacts
    artifacts: dist/*.whl dist/*.tar.gz
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !BranchUpdateTrigger
    projects: mdbf
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: Publish
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: SUCCESSFUL
    optional: false
  - !UseTemplateStep
    name: Detect Version
    templateName: Python Detect Version
    condition: SUCCESSFUL
    optional: false
  - !UseTemplateStep
    name: UV Cache and Sync
    templateName: UV Cache and Sync
    condition: SUCCESSFUL
    optional: false
  - !UseTemplateStep
    name: Publish to Local Registry
    templateName: UV Publish to OD PyPI
    paramMatrix:
    - name: access-token
      secret: true
      valuesProvider: !SpecifiedValues
        values:
        - - access-token
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !TagCreateTrigger {}
  jobDependencies:
  - jobName: CICD
    requireSuccessful: true
    artifacts: '**'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
imports:
- projectPath: buildspec_shared
  revision: main
  accessTokenSecret: buildspec-access-token
