version: 52
imports:
- projectPath: buildspec_shared
  revision: main
  accessTokenSecret: buildspec-access-token
jobs:
- name: CICD
  steps:
  - type: CheckoutStep
    name: Checkout
    cloneCredential:
      type: DefaultCredential
    withLfs: false
    withSubmodules: false
    condition: SUCCESSFUL
    optional: false
  - type: UseTemplateStep
    name: Detect Version
    templateName: Python Detect Version
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: UV Sync
    runInContainer: true
    image: ghcr.io/astral-sh/uv:debian-slim
    interpreter:
      type: PosixInterpreter
      shell: sh
      commands: |
        uv sync --python-preference=only-managed --locked
    runAs: 0:0
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - type: UseTemplateStep
    name: Linter
    templateName: Python Lint
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: Build Library
    runInContainer: true
    image: ghcr.io/astral-sh/uv:python3.13-bookworm-slim
    interpreter:
      type: PosixInterpreter
      shell: sh
      commands: |
        uv build --python-preference=only-managed
    runAs: 0:0
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - type: PublishArtifactStep
    name: Publish Artifacts
    artifacts: dist/*.whl dist/*.tar.gz
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    userMatch: anyone
    projects: mdbf
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: Publish
  steps:
  - type: CheckoutStep
    name: Checkout
    cloneCredential:
      type: DefaultCredential
    withLfs: false
    withSubmodules: false
    condition: SUCCESSFUL
    optional: false
  - type: UseTemplateStep
    name: Detect Version
    templateName: Python Detect Version
    condition: SUCCESSFUL
    optional: false
  - type: CommandStep
    name: UV Sync and Build
    runInContainer: true
    image: ghcr.io/astral-sh/uv:debian-slim
    interpreter:
      type: PosixInterpreter
      shell: sh
      commands: |
        uv sync --python-preference=only-managed --locked && uv build --python-preference=only-managed
    runAs: 0:0
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  - type: UseTemplateStep
    name: Publish to OneDev
    templateName: UV Publish
    paramMatrix:
    - valuesProvider:
        type: SpecifiedValues
        values:
        - - onedev
      secret: false
      name: index
    - valuesProvider:
        type: IgnoreValues
      secret: true
      name: token
    - valuesProvider:
        type: SpecifiedValues
        values:
        - - '@job_token@'
      secret: false
      name: username
    - valuesProvider:
        type: SpecifiedValues
        values:
        - - access-token
      secret: true
      name: password
    condition: SUCCESSFUL
    optional: false
  - type: UseTemplateStep
    name: Publish to PyPI
    templateName: UV Publish
    paramMatrix:
    - valuesProvider:
        type: IgnoreValues
      secret: false
      name: index
    - valuesProvider:
        type: SpecifiedValues
        values:
        - - pypi-token
      secret: true
      name: token
    - valuesProvider:
        type: IgnoreValues
      secret: false
      name: username
    - valuesProvider:
        type: IgnoreValues
      secret: true
      name: password
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: TagCreateTrigger
  jobDependencies:
  - jobName: CICD
    requireSuccessful: true
    artifacts: '**'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: GitHub Sync
  steps:
  - type: PullRepository
    name: Sync from GitHub
    remoteUrl: https://github.com/seaglade/mdbf.git
    userName: seaglade
    refs: refs/heads/* refs/tags/*
    withLfs: true
    force: false
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: ScheduleTrigger
    cronExpression: 0 0 0/3 * * ?
    branches: '**'
    projects: mdbf
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
