[project]
authors = [ { name = "KiARC", email = "kiarc@kiarc.win" } ]
dependencies = [
    "PyYAML>=6.0.3,<7",
    "py-cord>=2.8.0,<3",
    "toml>=0.10.2,<0.11",
]
description = "A Modular Discord Bot Framework based on pycord"
license = "GPL-3.0"
license-files = [ "LICENSE" ]
name = "mdbf"
readme = "README.md"
requires-python = ">=3.10,<3.15"
version = "1.0.0"

[dependency-groups]
dev = [
    "mypy>=2.2.0",
    "ruff>=0.15.21",
    "types-pyyaml>=6.0.12.20260518",
    "types-toml>=0.10.8.20260518",
]

[build-system]
build-backend = "uv_build"
requires = [ "uv_build~=0.8.3" ]

[[tool.uv.index]]
explicit = true
name = "onedev"
publish-url = "https://one.seaglade.dev/mdbf/~pypi"
url = "https://one.seaglade.dev/mdbf/~pypi/simple/"
