name: CICD
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
      - name: Set up python with uv
        run: uv python install
      - name: Sync dependencies
        run: uv sync --locked --all-extras --dev
      - name: Ruff Check
        uses: astral-sh/ruff-action@v3
      - name: MyPy Check
        run: uv run -- mypy --exclude .git --exclude .venv --check-untyped-defs .
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: lint
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v5
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
      - name: Set up python with uv
        run: uv python install
      - name: Sync dependencies
        run: uv sync --locked
      - name: Build
        run: uv build
      - name: Publish
        run: uv publish
